### PR TITLE
Redirect to login page from app when logged out

### LINKED ISSUE #141: Webapp can be used without logging in.
**Describe the bug**
I can access any page without having to login first.

**To Reproduce**
1. Start the webapp
2. Go to login page and login
3. Copy the URL
4. Go to a different browser or private browsing (of the same browser)
5. Paste the URL
6. Go to the URL

OR

1. Start the webapp
2. Go to localhost:3000/#/home/split
3. Create a bill
4. Press "Split Bill"

**Severity**
Mark with an x.
[x]: Minor effect eg. graphical
[]: Functional error eg. App does not function correctly
[]: Severe eg. Crashing

**Reproducibility**
Mark with an x.
[x]: Consistent
[]: Occasional
[]: Cannot reproduce at the moment eg. unsure

**Expected behavior**
I should be redirected to the login screen if I haven't already logged in on the browser.

**Screenshots, Images and Traces**
image
image
**Conditions**
I used Ubuntu OS with FireFox, FireFox Private Browsing and Chromium. I have not tested this on Windows OS.

**Additional context**
* The backend will return a message saying "User not logged in", meaning it is responding correctly to not logging in.
* Using the second set of instructions the new bill isn't saved due to the above stated error message.

### PR DESCRIPTION
**Pull request by timovv**
Fixes an issue where unauthorized users can access the Split app,
causing errors and undefined behaviour when they try to do things.

Closes #141.

**Description**

Write a simple description of the added feature or solution to the bug.
* Redirect to login page from app when logged out  
* Fixes an issue where unauthorized users can access the Split app,
    causing errors and undefined behaviour when they try to do things.

New files:
* `AuthorizedRoute.js` contains a routing component that which works similarly to `<Route />` but redirects the user if they are not logged in (this is tested by checking if there is an associated username. There might be a more robust test but this does work quite well).

**Testing**

Tried to access various endpoints within the app while logged out. Seems to be working fine.

**Checklist**

- [x] I have tested my change
- [x] Code builds successfully and all tests pass
- [ ] Docs have been added/updated if needed

### CODE REVIEW

File: split-webapp/split/src/components/AuthorizedRoute.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { Redirect, Route } from "react-router-dom";
+import React, { useContext } from "react";
+import { UserContext } from "../context/UserContext";
+
+const AuthorizedRoute = ({ path, component, exact }) =>
+  useContext(UserContext).username ? (
+    <Route path={path} component={component} exact={exact} />
+  ) : (
+    <Redirect to="/" />
```
Comment (ErnWong) [inline split-webapp/split/src/components/AuthorizedRoute.js]: I think this causes a redirection regardless of where you are - e.g. if you go to the signup page and hit refresh, this causes the page to be redirected to the login page, even though the signup route is not an `AuthorizedRoute`. Is this intended?

**Review by ErnWong — CHANGES_REQUESTED** [review]

File: split-webapp/split/src/App.js [hunk 2]
```diff
@@ -14,7 +15,7 @@ function App() {
           <header className="App-header">
             <div>
               <Route exact path="/" component={Login} />
-              <Route path="/home" component={Home} />
+              <AuthorizedRoute path="/home" component={Home} />
```
Comment (ErnWong) [inline split-webapp/split/src/App.js:18]: I'm noticing this problem:

Given the user is not logged in and has the login page `/` loaded,
When the user navigates to `/#/home/split` directly from the browser on the same tab as the loaded login page,
Then the app becomes blank.

I think this is because `/#/home` is not routed when the user is not logged in, and the `Redirect` has already been rendered and maybe there isn't anything to trigger a re-render.

This is different to loading `/#/home/split` in a new tab, where `Redirect` has yet to be rendered and redirects correctly.

**Review by ErnWong — CHANGES_REQUESTED** [review]

File: split-webapp/split/src/components/AuthorizedRoute.js (hunk 1 above)
Comment (timovv) [reply split-webapp/split/src/components/AuthorizedRoute.js]: Ah yeah, oops, I think I tested the sign in page by clicking on the link versus testing the route that should redirect by putting it into my browser. Fix should be pretty simple and is incoming.

**Comment by timovv** [comment]
Okay, cool, that's fixed, but I there's another issue that isn't fixed by this approach: you can access the login page while logged in, which makes no sense.

I think this should be a separate issue so I will make that now.

**Review by ErnWong — APPROVED** [review]
Looks good to me!

**Review by FrankWangma — APPROVED** [review]
Everything looks good to me. The fix works as expected
