### PR TITLE
top menu bar overlaps side bar in firefox and chrome

### LINKED ISSUE #127: Top menu bar overlaps side bar in Firefox and is overlapped in Chrome
**Describe the bug**
Notice how the top menu bar overlaps the side bar in Firefox:
image
Notice how this is not an issue in Chrome:
image

**To Reproduce**
1. Login in Firefox
2. Look at where the Sp/it logo is.

**Severity**
Mark with an x.
[x]: Minor effect eg. graphical
[]: Functional error eg. App does not function correctly
[]: Severe eg. Crashing

**Reproducibility**
Mark with an x.
[x]: Consistent
[]: Occasional
[]: Cannot reproduce at the moment eg. unsure

**Expected behavior**
Top menu should not overlap, nor should it be overlapped by, the side bar. I should probably be side by side with the sidebar.

* Implement as seen in Chrome.
* When the screen gets too small, use burger button to hide/show the sidebar

**Conditions**
Firefox for menu bar overlapping side bar.
Chrome for side bar overlapping menu bar.

**Issue Dependencies**
TODO

**Additional context**
TODO

### PR DESCRIPTION
**Pull request by clyanide**
Closes #127

**Description**

Write a simple description of the added feature or solution to the bug.
- Added top Padding to sidebar so that it no longer overlaps header
- Implemented the ability for the sidebar to expand and collapse in response to this [comment](https://github.com/se701-group6/A2/issues/127#issuecomment-609377704)

If necessary, describe what any new files are for
N/A

**Testing**

Manual testing was done with resizing

**Checklist**

- [x] I have tested my change
- [x] Code builds successfully and all tests pass
- [x] Docs have been added/updated if needed

### CODE REVIEW

File: split-webapp/split/src/pages/Home.js [hunk 1]
```diff
@@ -1,30 +1,69 @@
...
+
+    const SideBar = () => (
+      <div className="Sidebar">
+        <Button
+          className="SidebarButton"
+          variant="contained"
+          color="primary"
+          onClick={() => toggleSidebar()}
+        >
+          {"<<<"}
```
Comment (ErnWong) [inline split-webapp/split/src/pages/Home.js]: Rather than the `<<<`, what would be your thoughts on using the hamburger button from the top `MenuBar` to trigger the collapse instead, similar to [this mini variant drawer demo](https://material-ui.com/components/drawers/#mini-variant-drawer)?

Right now it looks a bit weird that we have both the hamburger button and the `<<<` `>>>` chevrons, but the hamburger button doesn't do anything.

File: split-webapp/split/src/App.css [hunk 2]
```diff
@@ -40,9 +40,37 @@
...
+  background-color: #79a2f4;
+  display: flex;
+  flex-direction: column;
+  position: absolute;
+  width: 3.5%;
+  height: 100%;
+  left: 0;
+  top: 0;
+  margin-top: 65px;
+  min-width: 70px;
```
Comment (ErnWong) [inline split-webapp/split/src/App.css]: A lot of this CSS is the same between the `.Sidebar` and `.CollapsedSidebar` classes. Do you reckon it would be good to avoid duplication by combining the shared properties into the following CSS rule?

```css
.Sidebar, .CollapsedSidebar {
  /* .... */
}
```

Similarly with the `.SidebarButton` and the `.CollapsedSidebarButton`.

File: split-webapp/split/src/pages/Home.js [hunk 3]
```diff
@@ -1,30 +1,69 @@
...
+      this.setState(prevState => ({ isOpen: !prevState.isOpen }));
+    };
+
+    const SideBar = () => (
+      <div className="Sidebar">
+        <Button
+          className="SidebarButton"
+          variant="contained"
+          color="primary"
+          onClick={() => toggleSidebar()}
```
Comment (ErnWong) [inline split-webapp/split/src/pages/Home.js]: Is the extra layer of arrow function necessary? Could it be simplified to this?

```js
onClick={toggleSidebar}
```

File: split-webapp/split/src/pages/Home.js [hunk 4]
```diff
@@ -1,30 +1,69 @@
...
+    const toggleSidebar = () => {
+      this.setState(prevState => ({ isOpen: !prevState.isOpen }));
+    };
+
+    const SideBar = () => (
+      <div className="Sidebar">
+        <Button
+          className="SidebarButton"
+          variant="contained"
+          color="primary"
```
Comment (ErnWong) [inline split-webapp/split/src/pages/Home.js]: How come we're setting this button as a contained primary button, but then we're changing the style to make it not look like a contained primary button? Would it be clearer if we only changed the text colour to the desired white?

(Or thoughts about using an [IconButton](https://material-ui.com/components/buttons/#icon-buttons)?)

File: split-webapp/split/src/pages/Home.js [hunk 5]
```diff
@@ -1,30 +1,69 @@
...
+      </div>
+    );
+
+    const { isOpen } = this.state;
+
+    return (
+      <HashRouter>
+        <MenuBar className="AppBar" />
+        <div>
+          {isOpen ? SideBar() : CollapsedSideBar()}
```
Comment (ErnWong) [inline split-webapp/split/src/pages/Home.js]: Would using the JSX style `<SideBar />` and `<CollapsedSideBar />` be clearer at conveying that react elements are being produced, rather than just function calls which usually return things other than react elements?

**Review by ErnWong — CHANGES_REQUESTED** [review]
Functionality wise - it looks very solid 👍 !

I threw a bunch of ideas and questions down in the comments - but feel free to argue against them if you disagree :)

File: split-webapp/split/src/App.css (hunk 2 above)
Comment (clifford1963) [reply split-webapp/split/src/App.css]: Thanks for the feedback. It would definitely be good to avoid duplication here. Just to clarify, although there are many similarities, there are also key differences such as the width of the bar (i.e. thin bar when collapsed, thick bar when expanded). If I were to combine it into a shared css rule like you mentioned, how/where should I specify the different bar widths?

Comment (ErnWong) [reply split-webapp/split/src/App.css]: One way would be to specify the differing CSS attributes in their own rules:

```css
.ClassA, .ClassB {
  /* ... shared attributes ... */
}
.ClassA {
  /* ... attributes for .ClassA only ... */
}
.ClassB {
  /* ... attributes for .ClassB only ... */
}
```

**Review by ErnWong — APPROVED** [review]
Looks good to me!

**Review by FrankWangma — APPROVED** [review]
Looking good. Fucntionality works
