### PR TITLE
Fixed invalid bills getting added (Issue #131)

### LINKED ISSUE #131: Invalid bills get added to database
**Describe the bug**
Trying to split a bill with insufficient information will get an error shown on the app, but the bill is still persisted and shown in the Transactions page. Fixing the bill by, e.g. adding more people or filling out the title/amount and resubmitting will add yet another new bill listed in the Transactions page, rather than fixing the previous invalid bill.

**To Reproduce**
1. Login to the app
2. Go to the 'Split a Bill' page
3. Without entering any information, click 'Split Bill'.
   Notice that this shows an error.
   Notice that the page does not change, implying that the app wants us to fix the error.
4. Enter some information for each field one by one, but click submit every time a new field is entered to re-trigger the error message.
4. Once all the required info has been entered, the app takes you to the 'Transactions' page.
5. Notice that a blank bill has been added along with many other incomplete bills, before the completed bill is shown.

**Severity**
Mark with an x.
[]: Minor effect eg. graphical
[x]: Functional error eg. App does not function correctly
[]: Severe eg. Crashing

**Reproducibility**
Mark with an x.
[x]: Consistent
[]: Occasional
[]: Cannot reproduce at the moment eg. unsure

**Expected behavior**
I do not expect invalid bills to be saved correctly. The frontend seems to perform some validation *after* sending the request to the server. The frontend should probably do the validation beforehand. Should the backend also perform some validation too?

**Screenshots, Images and Traces**
-

**Conditions**
Noticed on Ubuntu, Firefox, but should be platform agnostic.

**Issue Dependencies**
TODO

**Additional context**
TODO

### PR DESCRIPTION
**Pull request by xoneon**
Closes #131

**Description**

Fixes the issue where partial bills get added to the database when submitting incomplete bills:
Makes sure it checks whether the information entered is complete *before* creating the entry in the database, and returning if it's invalid.

**Testing**

Tested by attempting to replicate the bug described in the issue and seeing the correct behavior.
Specifically, press "split bill" without the complete information entered. Repeat as you enter information in each field one by one. Once finished, there should only be one entry added.

**Checklist**

- [x] I have tested my change
- [ ] Code builds successfully and all tests pass
- [ ] Docs have been added/updated if needed

### CODE REVIEW

**Review by ErnWong — APPROVED** [review]
Looks good!

File: split-webapp/split/src/pages/Split.js [hunk 1]
```diff
@@ -123,6 +105,24 @@ class Split extends Component {
       return;
     }
 
+    usersArray.forEach(user => {
+      if (user !== transaction.payed) {
```
Comment (timovv) [inline split-webapp/split/src/pages/Split.js:109]: nit: payed -> paid

Comment (timovv) [reply split-webapp/split/src/pages/Split.js:109]: Never mind, not your code, don't worry about it.

**Review by timovv — APPROVED** [review]
LGTM
